Unit LookyBook;

{---------------------------------------------------------------------------
This file generated by the IndySoap WSDL -> Pascal translator

Source:   http://hosting.msugs.ch/cheeso9/books/books.asmx?WSDL
Date:     24/8/2002 08:13:08
IndySoap: V0.02
Notes:
   Service LookyBookService.LookyBookServiceHttpGet ignored as no SOAP Address was specified
   Service LookyBookService.LookyBookServiceHttpPost ignored as no SOAP Address was specified
---------------------------------------------------------------------------}

Interface

Uses
  IdSoapClient,
  IdSoapTypeRegistry;

Type

  TbookInfoVendorprice = class;
  TbookInfo = class;

  TbookInfoVendorpriceArray = array of TbookInfoVendorprice;

  TbookInfoVendorprice = class (TIdBaseSoapableClass)
  Private
    Fname : String;
    FsiteUrl : String;
    FpricePrefix : String;
    Fprice : String;
  Published
    property name : String read Fname write Fname;
    property siteUrl : String read FsiteUrl write FsiteUrl;
    property pricePrefix : String read FpricePrefix write FpricePrefix;
    property price : String read Fprice write Fprice;
  end;

  TbookInfo = class (TIdBaseSoapableClass)
  Private
    Fisbn : String;
    Ftitle : String;
    Fauthor : String;
    Fpubdate : String;
    Fpublisher : String;
    FimgUrl : String;
    Ftimestamp : String;
    Fvendorprice : TbookInfoVendorpriceArray;
  Public
    Destructor Destroy; override;
    property vendorprice : TbookInfoVendorpriceArray read Fvendorprice write Fvendorprice;
  Published
    property isbn : String read Fisbn write Fisbn;
    property title : String read Ftitle write Ftitle;
    property author : String read Fauthor write Fauthor;
    property pubdate : String read Fpubdate write Fpubdate;
    property publisher : String read Fpublisher write Fpublisher;
    property imgUrl : String read FimgUrl write FimgUrl;
    property timestamp : String read Ftimestamp write Ftimestamp;
  end;


  {Soap Address for this Interface: http://hosting.msugs.ch/cheeso9/books/books.asmx}
  ILookyBook = Interface (IIdSoapInterface) ['{392FADD8-B8ED-4150-9F92-0F7EE2FF0C68}']
       {!Namespace: http://dinoch.dyndns.org/webservices/;
         SoapAction: http://dinoch.dyndns.org/webservices/GetInfo;
         Encoding: Document;
         Type: TbookInfo = bookInfo in http://dinoch.dyndns.org/bookService;
         Type: TbookInfoVendorprice = bookInfoVendorprice in http://dinoch.dyndns.org/bookService;
         Type: TbookInfoVendorpriceArray = bookInfoVendorpriceArray in http://dinoch.dyndns.org/bookService}
    function  GetInfo(ISBN : String) : TbookInfo; stdcall;
      {&retrieves book information for a given ISBN.  Returns an XML schema containing title, author, publisher, pubdate and other info.}
  end;

function GetILookyBook(AClient : TIdSoapBaseSender) : ILookyBook;

Implementation

{$R LookyBook.res}

uses
  IdSoapRTTIHelpers,
  IdSoapUtilities,
  SysUtils;


{ TbookInfo }

destructor TbookInfo.destroy;
var
  i: Integer;
begin
  for i := 0 to length(Fvendorprice) - 1 do
    begin
    FreeAndNil(Fvendorprice[i]);
    end;
  inherited;
end;

function GetILookyBook(AClient : TIdSoapBaseSender) : ILookyBook;
begin
  result := IdSoapD4Interface(AClient) as ILookyBook;
end;

Initialization
  IdSoapRegisterType(TypeInfo(TbookInfoVendorpriceArray), '', TypeInfo(TbookInfoVendorprice));
  IdSoapRegisterType(TypeInfo(TbookInfoVendorprice));
  IdSoapRegisterType(TypeInfo(TbookInfo));
  IdSoapRegisterProperty('TbookInfo', 'vendorprice',
                   IdSoapFieldProp(@TbookInfo(nil).Fvendorprice),
                   IdSoapFieldProp(@TbookInfo(nil).Fvendorprice),
                   TypeInfo(TbookInfoVendorpriceArray));
End.
